### ISSUE TITLE
spectral.js vs Mixbox

### ISSUE THREAD

**Issue by micycle1** [rvanwijnen/spectral.js#8]
Can you comment on how spectral.js differs (if at all) to [MixBox](https://github.com/scrtwpns/mixbox)?

**Comment by rvanwijnen** [comment]
The underlying math is the same in principle as both are based on the Kubelka-Munk theory.
The main difference is that Mixbox uses spectral dat from real pigments and I use generated spectral data.

As the spectral data is different the outcome can be different as well.

For example: Mixbox uses cadmium yellow which has some traces of green in the spectral data, therefor if it’s mixed with cobalt blue it creates a richer green than spectral.js is able too because spectral.js is lacking the traces of green.
